set(_CATKIN_CURRENT_PACKAGE "asv_wave_sim_gazebo")
set(asv_wave_sim_gazebo_VERSION "0.1.2")
set(asv_wave_sim_gazebo_MAINTAINER "Rhys Mainwaring <rhys.mainwaring@me.com>")
set(asv_wave_sim_gazebo_PACKAGE_FORMAT "2")
set(asv_wave_sim_gazebo_BUILD_DEPENDS )
set(asv_wave_sim_gazebo_BUILD_EXPORT_DEPENDS )
set(asv_wave_sim_gazebo_BUILDTOOL_DEPENDS "catkin")
set(asv_wave_sim_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(asv_wave_sim_gazebo_EXEC_DEPENDS "asv_wave_sim_gazebo_plugins" "gazebo_ros" "roslaunch")
set(asv_wave_sim_gazebo_RUN_DEPENDS "asv_wave_sim_gazebo_plugins" "gazebo_ros" "roslaunch")
set(asv_wave_sim_gazebo_TEST_DEPENDS )
set(asv_wave_sim_gazebo_DOC_DEPENDS )
set(asv_wave_sim_gazebo_URL_WEBSITE "https://github.com/srmainwaring/asv_wave_sim")
set(asv_wave_sim_gazebo_URL_BUGTRACKER "https://github.com/srmainwaring/asv_wave_sim/issues")
set(asv_wave_sim_gazebo_URL_REPOSITORY "https://github.com/srmainwaring/asv_wave_sim")
set(asv_wave_sim_gazebo_DEPRECATED "")