set(_CATKIN_CURRENT_PACKAGE "asv_wave_sim_gazebo_plugins")
set(asv_wave_sim_gazebo_plugins_VERSION "0.1.2")
set(asv_wave_sim_gazebo_plugins_MAINTAINER "Rhys Mainwaring <rhys.mainwaring@me.com>")
set(asv_wave_sim_gazebo_plugins_PACKAGE_FORMAT "2")
set(asv_wave_sim_gazebo_plugins_BUILD_DEPENDS "cgal" "eigen" "gazebo_ros")
set(asv_wave_sim_gazebo_plugins_BUILD_EXPORT_DEPENDS "cgal" "eigen" "gazebo_ros")
set(asv_wave_sim_gazebo_plugins_BUILDTOOL_DEPENDS "catkin")
set(asv_wave_sim_gazebo_plugins_BUILDTOOL_EXPORT_DEPENDS )
set(asv_wave_sim_gazebo_plugins_EXEC_DEPENDS "cgal" "eigen" "gazebo_ros")
set(asv_wave_sim_gazebo_plugins_RUN_DEPENDS "cgal" "eigen" "gazebo_ros")
set(asv_wave_sim_gazebo_plugins_TEST_DEPENDS )
set(asv_wave_sim_gazebo_plugins_DOC_DEPENDS )
set(asv_wave_sim_gazebo_plugins_URL_WEBSITE "https://github.com/srmainwaring/asv_wave_sim")
set(asv_wave_sim_gazebo_plugins_URL_BUGTRACKER "https://github.com/srmainwaring/asv_wave_sim/issues")
set(asv_wave_sim_gazebo_plugins_URL_REPOSITORY "https://github.com/srmainwaring/asv_wave_sim")
set(asv_wave_sim_gazebo_plugins_DEPRECATED "")