set(_CATKIN_CURRENT_PACKAGE "sailboat_sim")
set(sailboat_sim_VERSION "0.0.0")
set(sailboat_sim_MAINTAINER "sharon <sharon@todo.todo>")
set(sailboat_sim_PACKAGE_FORMAT "2")
set(sailboat_sim_BUILD_DEPENDS "roscpp" "rospy" "urdf" "xacro" "tf2" "tf2_ros")
set(sailboat_sim_BUILD_EXPORT_DEPENDS "tf2" "tf2_ros")
set(sailboat_sim_BUILDTOOL_DEPENDS "catkin")
set(sailboat_sim_BUILDTOOL_EXPORT_DEPENDS )
set(sailboat_sim_EXEC_DEPENDS "roscpp" "rospy" "urdf" "xacro" "joint_state_publisher" "joint_state_publisher_gui" "robot_state_publisher" "rviz" "tf2" "tf2_ros")
set(sailboat_sim_RUN_DEPENDS "roscpp" "rospy" "urdf" "xacro" "joint_state_publisher" "joint_state_publisher_gui" "robot_state_publisher" "rviz" "tf2" "tf2_ros")
set(sailboat_sim_TEST_DEPENDS )
set(sailboat_sim_DOC_DEPENDS )
set(sailboat_sim_URL_WEBSITE "")
set(sailboat_sim_URL_BUGTRACKER "")
set(sailboat_sim_URL_REPOSITORY "")
set(sailboat_sim_DEPRECATED "")