# CMake generated Testfile for 
# Source directory: /home/sharon/catkin_ws/src/asv_wave_sim/asv_wave_sim_gazebo_plugins
# Build directory: /home/sharon/catkin_ws/build_isolated/asv_wave_sim_gazebo_plugins
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_asv_wave_sim_gazebo_plugins_gtest_UNIT_Algorithm_TEST "/home/sharon/catkin_ws/build_isolated/asv_wave_sim_gazebo_plugins/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/sharon/catkin_ws/build_isolated/asv_wave_sim_gazebo_plugins/test_results/asv_wave_sim_gazebo_plugins/gtest-UNIT_Algorithm_TEST.xml" "--return-code" "/home/sharon/catkin_ws/devel_isolated/asv_wave_sim_gazebo_plugins/lib/asv_wave_sim_gazebo_plugins/UNIT_Algorithm_TEST --gtest_output=xml:/home/sharon/catkin_ws/build_isolated/asv_wave_sim_gazebo_plugins/test_results/asv_wave_sim_gazebo_plugins/gtest-UNIT_Algorithm_TEST.xml")
set_tests_properties(_ctest_asv_wave_sim_gazebo_plugins_gtest_UNIT_Algorithm_TEST PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/sharon/catkin_ws/src/asv_wave_sim/asv_wave_sim_gazebo_plugins/CMakeLists.txt;335;catkin_add_gtest;/home/sharon/catkin_ws/src/asv_wave_sim/asv_wave_sim_gazebo_plugins/CMakeLists.txt;0;")
add_test(_ctest_asv_wave_sim_gazebo_plugins_gtest_UNIT_CGAL_TEST "/home/sharon/catkin_ws/build_isolated/asv_wave_sim_gazebo_plugins/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/sharon/catkin_ws/build_isolated/asv_wave_sim_gazebo_plugins/test_results/asv_wave_sim_gazebo_plugins/gtest-UNIT_CGAL_TEST.xml" "--return-code" "/home/sharon/catkin_ws/devel_isolated/asv_wave_sim_gazebo_plugins/lib/asv_wave_sim_gazebo_plugins/UNIT_CGAL_TEST --gtest_output=xml:/home/sharon/catkin_ws/build_isolated/asv_wave_sim_gazebo_plugins/test_results/asv_wave_sim_gazebo_plugins/gtest-UNIT_CGAL_TEST.xml")
set_tests_properties(_ctest_asv_wave_sim_gazebo_plugins_gtest_UNIT_CGAL_TEST PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/sharon/catkin_ws/src/asv_wave_sim/asv_wave_sim_gazebo_plugins/CMakeLists.txt;339;catkin_add_gtest;/home/sharon/catkin_ws/src/asv_wave_sim/asv_wave_sim_gazebo_plugins/CMakeLists.txt;0;")
add_test(_ctest_asv_wave_sim_gazebo_plugins_gtest_UNIT_Geometry_TEST "/home/sharon/catkin_ws/build_isolated/asv_wave_sim_gazebo_plugins/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/sharon/catkin_ws/build_isolated/asv_wave_sim_gazebo_plugins/test_results/asv_wave_sim_gazebo_plugins/gtest-UNIT_Geometry_TEST.xml" "--return-code" "/home/sharon/catkin_ws/devel_isolated/asv_wave_sim_gazebo_plugins/lib/asv_wave_sim_gazebo_plugins/UNIT_Geometry_TEST --gtest_output=xml:/home/sharon/catkin_ws/build_isolated/asv_wave_sim_gazebo_plugins/test_results/asv_wave_sim_gazebo_plugins/gtest-UNIT_Geometry_TEST.xml")
set_tests_properties(_ctest_asv_wave_sim_gazebo_plugins_gtest_UNIT_Geometry_TEST PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/sharon/catkin_ws/src/asv_wave_sim/asv_wave_sim_gazebo_plugins/CMakeLists.txt;343;catkin_add_gtest;/home/sharon/catkin_ws/src/asv_wave_sim/asv_wave_sim_gazebo_plugins/CMakeLists.txt;0;")
add_test(_ctest_asv_wave_sim_gazebo_plugins_gtest_UNIT_Grid_TEST "/home/sharon/catkin_ws/build_isolated/asv_wave_sim_gazebo_plugins/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/sharon/catkin_ws/build_isolated/asv_wave_sim_gazebo_plugins/test_results/asv_wave_sim_gazebo_plugins/gtest-UNIT_Grid_TEST.xml" "--return-code" "/home/sharon/catkin_ws/devel_isolated/asv_wave_sim_gazebo_plugins/lib/asv_wave_sim_gazebo_plugins/UNIT_Grid_TEST --gtest_output=xml:/home/sharon/catkin_ws/build_isolated/asv_wave_sim_gazebo_plugins/test_results/asv_wave_sim_gazebo_plugins/gtest-UNIT_Grid_TEST.xml")
set_tests_properties(_ctest_asv_wave_sim_gazebo_plugins_gtest_UNIT_Grid_TEST PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/sharon/catkin_ws/src/asv_wave_sim/asv_wave_sim_gazebo_plugins/CMakeLists.txt;347;catkin_add_gtest;/home/sharon/catkin_ws/src/asv_wave_sim/asv_wave_sim_gazebo_plugins/CMakeLists.txt;0;")
add_test(_ctest_asv_wave_sim_gazebo_plugins_gtest_UNIT_Physics_TEST "/home/sharon/catkin_ws/build_isolated/asv_wave_sim_gazebo_plugins/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/sharon/catkin_ws/build_isolated/asv_wave_sim_gazebo_plugins/test_results/asv_wave_sim_gazebo_plugins/gtest-UNIT_Physics_TEST.xml" "--return-code" "/home/sharon/catkin_ws/devel_isolated/asv_wave_sim_gazebo_plugins/lib/asv_wave_sim_gazebo_plugins/UNIT_Physics_TEST --gtest_output=xml:/home/sharon/catkin_ws/build_isolated/asv_wave_sim_gazebo_plugins/test_results/asv_wave_sim_gazebo_plugins/gtest-UNIT_Physics_TEST.xml")
set_tests_properties(_ctest_asv_wave_sim_gazebo_plugins_gtest_UNIT_Physics_TEST PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/sharon/catkin_ws/src/asv_wave_sim/asv_wave_sim_gazebo_plugins/CMakeLists.txt;351;catkin_add_gtest;/home/sharon/catkin_ws/src/asv_wave_sim/asv_wave_sim_gazebo_plugins/CMakeLists.txt;0;")
add_test(_ctest_asv_wave_sim_gazebo_plugins_gtest_UNIT_TriangulatedGrid_TEST "/home/sharon/catkin_ws/build_isolated/asv_wave_sim_gazebo_plugins/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/sharon/catkin_ws/build_isolated/asv_wave_sim_gazebo_plugins/test_results/asv_wave_sim_gazebo_plugins/gtest-UNIT_TriangulatedGrid_TEST.xml" "--return-code" "/home/sharon/catkin_ws/devel_isolated/asv_wave_sim_gazebo_plugins/lib/asv_wave_sim_gazebo_plugins/UNIT_TriangulatedGrid_TEST --gtest_output=xml:/home/sharon/catkin_ws/build_isolated/asv_wave_sim_gazebo_plugins/test_results/asv_wave_sim_gazebo_plugins/gtest-UNIT_TriangulatedGrid_TEST.xml")
set_tests_properties(_ctest_asv_wave_sim_gazebo_plugins_gtest_UNIT_TriangulatedGrid_TEST PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/sharon/catkin_ws/src/asv_wave_sim/asv_wave_sim_gazebo_plugins/CMakeLists.txt;355;catkin_add_gtest;/home/sharon/catkin_ws/src/asv_wave_sim/asv_wave_sim_gazebo_plugins/CMakeLists.txt;0;")
add_test(_ctest_asv_wave_sim_gazebo_plugins_gtest_UNIT_Wavefield_TEST "/home/sharon/catkin_ws/build_isolated/asv_wave_sim_gazebo_plugins/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/sharon/catkin_ws/build_isolated/asv_wave_sim_gazebo_plugins/test_results/asv_wave_sim_gazebo_plugins/gtest-UNIT_Wavefield_TEST.xml" "--return-code" "/home/sharon/catkin_ws/devel_isolated/asv_wave_sim_gazebo_plugins/lib/asv_wave_sim_gazebo_plugins/UNIT_Wavefield_TEST --gtest_output=xml:/home/sharon/catkin_ws/build_isolated/asv_wave_sim_gazebo_plugins/test_results/asv_wave_sim_gazebo_plugins/gtest-UNIT_Wavefield_TEST.xml")
set_tests_properties(_ctest_asv_wave_sim_gazebo_plugins_gtest_UNIT_Wavefield_TEST PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/sharon/catkin_ws/src/asv_wave_sim/asv_wave_sim_gazebo_plugins/CMakeLists.txt;359;catkin_add_gtest;/home/sharon/catkin_ws/src/asv_wave_sim/asv_wave_sim_gazebo_plugins/CMakeLists.txt;0;")
add_test(_ctest_asv_wave_sim_gazebo_plugins_gtest_UNIT_WaveSimulation_TEST "/home/sharon/catkin_ws/build_isolated/asv_wave_sim_gazebo_plugins/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/sharon/catkin_ws/build_isolated/asv_wave_sim_gazebo_plugins/test_results/asv_wave_sim_gazebo_plugins/gtest-UNIT_WaveSimulation_TEST.xml" "--return-code" "/home/sharon/catkin_ws/devel_isolated/asv_wave_sim_gazebo_plugins/lib/asv_wave_sim_gazebo_plugins/UNIT_WaveSimulation_TEST --gtest_output=xml:/home/sharon/catkin_ws/build_isolated/asv_wave_sim_gazebo_plugins/test_results/asv_wave_sim_gazebo_plugins/gtest-UNIT_WaveSimulation_TEST.xml")
set_tests_properties(_ctest_asv_wave_sim_gazebo_plugins_gtest_UNIT_WaveSimulation_TEST PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/sharon/catkin_ws/src/asv_wave_sim/asv_wave_sim_gazebo_plugins/CMakeLists.txt;363;catkin_add_gtest;/home/sharon/catkin_ws/src/asv_wave_sim/asv_wave_sim_gazebo_plugins/CMakeLists.txt;0;")
subdirs("gtest")
