set(_CATKIN_CURRENT_PACKAGE "asv_wave_sim")
set(asv_wave_sim_VERSION "0.1.2")
set(asv_wave_sim_MAINTAINER "Rhys Mainwaring <rhys.mainwaring@me.com>")
set(asv_wave_sim_PACKAGE_FORMAT "2")
set(asv_wave_sim_BUILD_DEPENDS )
set(asv_wave_sim_BUILD_EXPORT_DEPENDS )
set(asv_wave_sim_BUILDTOOL_DEPENDS "catkin")
set(asv_wave_sim_BUILDTOOL_EXPORT_DEPENDS )
set(asv_wave_sim_EXEC_DEPENDS "asv_wave_sim_gazebo" "asv_wave_sim_gazebo_plugins")
set(asv_wave_sim_RUN_DEPENDS "asv_wave_sim_gazebo" "asv_wave_sim_gazebo_plugins")
set(asv_wave_sim_TEST_DEPENDS )
set(asv_wave_sim_DOC_DEPENDS )
set(asv_wave_sim_URL_WEBSITE "https://github.com/srmainwaring/asv_wave_sim")
set(asv_wave_sim_URL_BUGTRACKER "https://github.com/srmainwaring/asv_wave_sim/issues")
set(asv_wave_sim_URL_REPOSITORY "https://github.com/srmainwaring/asv_wave_sim")
set(asv_wave_sim_DEPRECATED "")